### ISSUE TITLE
Persistent Cross-Site Scripting in Zoo-Management-System

### ISSUE THREAD

**Issue by prasadlingamaiah** [jedaademola/Zoo-Management-System#19]
**Stored Cross-Site Scripting Vulnerability**

**Description:** Stored XSS, also known as persistent XSS, is more damaging than non-persistent XSS. It occurs when a malicious script is injected directly into a vulnerable web application. Cross-site scripting is a web security vulnerability that allows an attacker to compromise the interactions that users have with a vulnerable application. It allows an attacker to circumvent the same-origin policy, which is designed to segregate different websites from each other. Cross-site scripting vulnerabilities normally allow an attacker to masquerade as a victim user, to carry out any actions that the user is able to perform and to access any of the user's data. If the victim user has privileged access within the application, then the attacker might be able to gain full control over all of the application's functionality and data

**Steps to Reproduce:**

Step 1: log in to the application
![image](https://user-images.githubusercontent.com/24879082/115069704-99e34180-9f11-11eb-9497-46575a324793.png)

Step 2: Navigate to about us location using the http://127.0.0.1/Zoo-Management-System-Project/Zoo%20Management%20System%20Project/zms/admin/aboutus.php
![image](https://user-images.githubusercontent.com/24879082/115069761-ac5d7b00-9f11-11eb-9773-9c53f082272c.png)

Step 3:  Insert a malicious HTML payload and update it
![image](https://user-images.githubusercontent.com/24879082/115069871-d6af3880-9f11-11eb-9178-815d2bc212f3.png)
![image](https://user-images.githubusercontent.com/24879082/115070063-10803f00-9f12-11eb-9f8e-9d7390994f70.png)

Step 4: Now go to the home page access the about us page using the 
![image](https://user-images.githubusercontent.com/24879082/115070206-40c7dd80-9f12-11eb-9d62-c946c9be6538.png)

**Expected Result:**
The application will render using the xss popup
Mitigation:
Preventing cross-site scripting is trivial in some cases but can be much harder depending on the complexity of the application and the ways it handles user-controllable data.

In general, effectively preventing XSS vulnerabilities is likely to involve a combination of the following measures:
Filter input on arrival. At the point where user input is received, filter as strictly as possible based on what is expected or valid input.
Encode data on output. At the point where user-controllable data is output in HTTP responses, encode the output to prevent it from being interpreted as active content. Depending on the output context, this might require applying combinations of HTML, URL, JavaScript, and CSS encoding.
Use appropriate response headers. To prevent XSS in HTTP responses that aren't intended to contain any HTML or JavaScript, you can use the Content-Type and X-Content-Type-Options headers to ensure that browsers interpret the responses in the way you intend.
Content Security Policy. As a last line of defense, you can use Content Security Policy (CSP) to reduce the severity of any XSS vulnerabilities that still occur.

Output encoding:
It is recommended to implement ‘output encoding’ to convert untrusted input into a safe form where the input is displayed as data to the user without executing as code in the browser. Java HTML encoding Function public static String HTMLEncode(String aTagFragment){ final StringBuffer result = new StringBuffer(); final StringCharacterIterator iterator = new StringCharacterIterator(aTagFragment); char character = iterator.current(); while (character != StringCharacterIterator.DONE ) { if (character == '<') result.append("<"); else if (character == '>') result.append(">"); else if (character == '"') result.append("""); else if (character == ''') result.append("'"); else if (character == '') result.append(""); else if (character == '&') result.append("&"); else { //the char is not a special one //add it to the result as is result.append(character); } character = iterator.next(); } return result.toString(); } • Escaping: Escape all untrusted data based on the HTML context (body, attribute, JavaScript, CSS, or URL) that the data will be placed into. EASPI API String safe = ESAPI.encoder().encodeForHTML( request.getParameter( "input" ) );
• Filtering input parameter: Positive or "whitelist" input validation with appropriate canonicalization is the recommended filtering technique. Alternatively, black-list filtering input works by removing some or all special characters from your input. Special characters are characters that enable script to be generated within an HTML stream. Special characters include the following: <> " ' % ; ) ( & + - JavaScript Codefunction RemoveBad(strTemp) { strTemp = strTemp.replace(/<|>|"|'|%|;|(|)|&|+|-/g,""); return strTemp; }

**Comment by jedaademola** [comment]
Thank you for the information and recommendation.

**Comment by jedaademola** [comment]
closed
